name: Update Package Version

on:
  push:
    tags:
      - '*internal*'
      - '*beta*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: test-version
      
      - name: Update version in package.json
        run: |
          VERSION=$GITHUB_REF_NAME
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"


          sed -i 's/"version": "[^"]*"/"version": "'"$VERSION"'"/' package.json
          git add package.json
          if [ $(git status --porcelain | wc -l) -eq "0" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git --no-pager diff
          git commit -m "Changes made by GitHub Actions [skip ci]"
          git push origin test-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
